[build]
command = "npm run build"
publish = ".next"

[functions]
node_bundler = "esbuild"
external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]
included_files = ["node_modules/@sparticuz/chromium/bin/**"]
memory = 3072
timeout = 26

[[plugins]]
package = "@netlify/plugin-nextjs"
